name: "Deploy GitHub Pages"
run-name: "Deploy GitHub Pages"

on:

  schedule:
    - cron: '0 0 1 * *'

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: "Build GitHub Pages"
    uses: ./.github/workflows/build.yml

  deploy:
    if: github.ref_name == 'main'
    name: "Deploy GitHub Pages"
    needs: build
    runs-on: ubuntu-latest

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: configure-pages
        name: "Setup Pages"
        uses: actions/configure-pages@v5
        
      - name: "Unarchive Pages Artifact"
        uses: actions/download-artifact@v4
        with:
          name: pages

      - name: "Create a Pages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: "Deploy Pages"
        uses: actions/deploy-pages@v4
