name: "Deploy GitHub Pages"
run-name: "Deploy GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    if: github.ref_name == 'main'
    needs: build
    runs-on: ubuntu-latest

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Setup Pages"
        uses: actions/configure-pages@v3
        
      - name: "Unarchive Pages Artifact"
        uses: actions/download-artifact@v4.1.7
        with:
          name: pages

      - name: "Generate a security.txt file"
        run: |
          tee security.txt << EOF
          Contact: $(gh api '/repos/${{ github.repository }}' --jq '.homepage')/contact
          Policy: $(gh api '/repos/${{ github.repository }}' --jq '.homepage')/security/policy
          Acknowledgments: $(gh api '/repos/${{ github.repository }}' --jq '.homepage')/humans.txt
          Canonical: $(gh api '/repos/${{ github.repository }}' --jq '.homepage')/security.txt
          Expires: $(date -u +"%Y-12-31T23:59:59.999Z")
          EOF

      - name: "Generate a humans.txt file"
        run: gh api "${ENDPOINT}" --template "${TEMPLATE}" | sh | tee humans.txt
        env:
          ENDPOINT: '/orgs/${{ github.repository_owner }}/repos'
          TEMPLATE: |
            echo "# Contributors by Repository"
            echo
            echo "A huge thanks to all and colaborators who have contributed on GitHub!"
            echo
            {{range .}}
            echo "## {{.full_name}}"
            echo
            gh api '/repos/{{.full_name}}/contributors' --jq '.[].login' | sort -u | xargs -ILOGIN gh api '/users/LOGIN' --jq '"- @" + .login + " (" + (.name // .login) + ")"'
            echo
            {{end}}

      - name: "Generate a robots.txt file"
        run: |
          tee security.txt << EOF
          Sitemap: $(gh api '/repos/${{ github.repository }}' --jq '.homepage')/sitemap.txt
          EOF

      - name: "Generate a sitemap.txt file"
        run: |
          tee sitemap.txt << EOF 
          $(
            find . -type f -printf '%P\n' | \
            grep -v '^\.' | \
            sed -e 's/\(\.html\)*$//g' | \
            sort | \
            uniq | \
            xargs -IPATH gh api '/repos/${{ github.repository }}' --jq '.homepage + "/PATH"'
          )
          EOF

      - name: "Create a Pages Artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: "Deploy Pages"
        uses: actions/deploy-pages@v1
